version: 2.1

# Setup remote docker environment
# https://circleci.com/docs/2.0/building-docker-images/
orbs:
  kubernetes: circleci/kubernetes@1.3.1

executors:
  docker-environment:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: {YOUR_USERNAME}/{YOUR_DOCKERREPO}

jobs:
  build:
    executor: docker-environment
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true # DLC will explicitly cache layers here and try to avoid rebuilding.
    - run:
        name: "Docker build"
        command: docker build src/connect4-client -t $IMAGE_NAME:$CIRCLE_SHA1
    - run:
        name: "Docker save"
        command: docker save -o image.tar $IMAGE_NAME      
    - persist_to_workspace:
        root: .
        paths:
          - ./image.tar
  publish:
    executor: docker-environment
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run: 
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1
  deploy:
    executor: docker-environment
    steps:
      - checkout
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - run:
          name: "Generating connect4 client yaml"
          command: ./scripts/ci/yaml/merge.sh "./src/connect4-client/k8s" | sed "s/{{IMAGE_TAG}}/${CIRCLE_SHA1}/g" > connect4-client.yaml
      - run:
          name: "Deploy"
          command: echo "Deploying connect4-client" && kubectl apply -f connect4-client.yaml

# Only deploy when main branch is updated   
workflows:
  pipeline:
    jobs:
    - build
    - publish:
        requires:
          - build
    - deploy:
        requires:
          - publish
        filters:
          branches:
            only: main

# VS Code Extension Version: 1.1.1
